import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavMenu from "@/app/NavMenu";
import "./globals.css";
import AuthProvider from "@/app/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
        <NavMenu />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
